### PR TITLE
Switch to pylsp and rename to LSP-pylsp

### PR DESCRIPTION
**Pull request by rchl**
Hard to say for sure if all the options still match the new project. Spent some time to switch out `pyls_mypy` for `mypy_ls` at least and verified that it's working.

The repo will be renamed to LSP-pylsp also later.

### CODE REVIEW

**Comment by predragnikolic** [comment]
How did you extract all the setting configurations?

I saw that you covered almost all, but there are maybe some missing like `plugins.pycodestyle.aggressive`: (If I notice some other I will let you know)
https://github.com/python-lsp/python-lsp-server/blob/develop/pylsp/config/pycodestyle_conf.py#L20

**Comment by rchl** [comment]
I've just reused the settings that @rwols set up for pyls with the exception of replacing `pyls_mypy` with `mypy-ls`.

**Comment by predragnikolic** [comment]
I cloned the https://github.com/python-lsp/python-lsp-server repo
and did a global find in project `plugins.` and noticed these settings missing:

```
C:\Users\Predrag\Documents\python-lsp-server\pylsp\config\flake8_conf.py:
   24      # flake8
   25:     ('exclude', 'plugins.flake8.exclude', list),
   26:     ('filename', 'plugins.flake8.filename', list),
   27:     ('hang-closing', 'plugins.flake8.hangClosing', bool),
   28:     ('ignore', 'plugins.flake8.ignore', list),
   29:     ('max-line-length', 'plugins.flake8.maxLineLength', int),
   30:     ('select', 'plugins.flake8.select', list),
   31:     ('per-file-ignores', 'plugins.flake8.perFileIgnores', list),


C:\Users\Predrag\Documents\python-lsp-server\pylsp\config\pycodestyle_conf.py:
   20:     ('aggressive', 'plugins.pycodestyle.aggressive', int),
```

**Comment by rchl** [comment]
Thanks.

**Comment by rchl** [comment]
I'm thinking that it would be better to instead create a new repo for it and archive this one.

**Review by rwols — APPROVED** [review]

**Comment by rchl** [comment]
So no separate repo then?

**Comment by rwols** [comment]
too much effort :)

**Pull request merged**
